from enum import Enum

class Job_type(Enum):
    FUERZAS_MILITARES = 1
    DIRECTORES_GERENTES = 2
    PROFESIONALES_CIENTIFICOS = 3
    TECNICOS_PROFESIONALES = 4
    PERSONAL_APOYO_ADM = 5
    TRABAJADORES_VENDEDORES = 6